### ISSUE TITLE
how to build the docs

### ISSUE THREAD

**Issue by lemuellew** [chaoticgd/ghidra-decompiler-docs-built#1]
Thank you very much for  the documentations. Could you please tell me how to build these documents from Ghidra repo？

**Comment by chaoticgd** [comment]
Hi,

Sorry about the late reply, I barely ever get any emails on here.
If you're on Linux, you can cd into the decompiler source code directory and
run doxygen on the command line. Not sure about Windows/macOS.

The path your need is: Ghidra/Features/Decompiler/src/decompile/cpp

Thanks,
chaoticgd

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
